import { config } from "dotenv"
config({ path: ".env.local" }); config()
import { prisma } from "../lib/prisma"
import { ELITE_SHOWCASES } from "../lib/showcases-data"

const OWNER = process.env.SHOWCASE_OWNER_ID ?? "user_3IGDYw03LkmHZaaCgKwWcBYxHQu"
const topics: Record<string, any> = {
 "vla-autonomous-surgery": {authors:"Maya Chen, Elias Novak, Priya Raman, Luca Moretti",venue:"CVPR 2027 • Embodied AI for Medicine",poster:"betterposter",paper:"cvpr", color:"#00A6A6", claim:"SurgiVLA couples a multimodal policy to a control-barrier safety shield, achieving 98.7% success and 0.31 mm median endpoint error on 1,240 ex-vivo trials.", equation:"a_t = \\arg\\min_a \\|a-\\pi_\\theta(o_{\\le t},l)\\|_2^2 \\; \\text{s.t.} \\; \\dot h(x,a)+\\alpha h(x)\\ge 0", methods:"A 7B-parameter vision-language backbone consumes stereo endoscopy, force telemetry, language intent, and robot state. A 42 Hz diffusion action head predicts 16-step trajectories; conformal uncertainty triggers a certified safe-stop.", table:[["Method","Success ↑","Error ↓","Latency ↓"],["BC-Z","71.4%","1.42 mm","18 ms"],["RT-2","79.8%","0.93 mm","96 ms"],["OpenVLA","86.2%","0.71 mm","61 ms"],["**SurgiVLA**","**98.7%**","**0.31 mm**","**23.8 ms**"]]},
 "neural-wavefunction-superconductors": {authors:"Amara Okafor, Jonas Klein, Sofia Petrov",venue:"APS March Meeting 2027 • Quantum Matter",poster:"atlas",paper:"revtex-aps",color:"#6D5DFB",claim:"An E(3)-equivariant neural quantum state resolves anharmonic electron-phonon coupling and predicts a 287 K transition in metastable LaH10-xNx at 182 GPa.",equation:"\\Psi_\\theta(R)=\\det[\\phi_i(r_j)]\\exp[J_\\theta(R)],\\qquad E_\\theta=\\frac{\\langle\\Psi_\\theta|\\hat H|\\Psi_\\theta\\rangle}{\\langle\\Psi_\\theta|\\Psi_\\theta\\rangle}",methods:"Equivariant message passing parameterizes orbitals and a long-range Jastrow factor. Stochastic reconfiguration minimizes variational energy over 65,536 walkers with twist averaging and finite-size extrapolation.",table:[["Method","Tc (K) ↑","Energy err. ↓","Samples/s ↑"],["DFT-PBE","214","18.7 meV","1.0×"],["SCDFT","242","11.3 meV","0.4×"],["FermiNet-VMC","268","4.8 meV","1.7×"],["**Eq-NQS**","**287**","**2.4 meV**","**8.1×**"]]},
 "cas13-panviral-immunity": {authors:"Noor Al-Sayed, Hannah Brooks, Kenji Watanabe, Ana Silva",venue:"Nature Biotechnology Methods Forum 2027",poster:"gemini",paper:"neurips",color:"#E45756",claim:"EvoGuide designs structure-aware Cas13d guide ensembles that knock down 99.2% of viral RNA while preventing detectable escape across 48 serial cultures.",equation:"\\mathcal L=\\mathcal L_{\\text{cleavage}}+0.4\\mathcal L_{\\text{access}}+0.7\\max_{v\\in\\mathcal V}\\mathcal L_{\\text{escape}}(v)+10^{-3}\\|\\theta\\|_2^2",methods:"A pangenome transformer scores conservation, RNA accessibility, collateral-risk, and mutational escape. Submodular selection returns four-guide ensembles under manufacturability and off-target constraints.",table:[["Design","Knockdown ↑","Escape cultures ↓","Off-targets ↓"],["siRNA","72.1%","19/48","7"],["Cas13-single","91.6%","11/48","3"],["Random-4","96.8%","4/48","2"],["**EvoGuide-4**","**99.2%**","**0/48**","**0**"]]}
}
const bib=`@article{vaswani2017attention,title={Attention Is All You Need},author={Vaswani, Ashish and others},journal={NeurIPS},year={2017}}
@article{brohan2023rt2,title={RT-2: Vision-Language-Action Models},author={Brohan, Anthony and others},journal={CoRL},year={2023}}
@article{pfau2020abinitio,title={Ab-initio Solution of the Electronic Schrödinger Equation},author={Pfau, David and others},journal={Physical Review Research},year={2020}}
@article{abudayyeh2017rna,title={RNA targeting with CRISPR-Cas13},author={Abudayyeh, Omar and others},journal={Nature},year={2017}}`
const emptyTable={hasHeader:false,caption:"",rows:[] as string[][]}
function card(id:string,title:string,pattern:string,content:string,column:number|null,order:number, extra:any={}) {return {id,title,pattern,content,column,order,figureLayout:"single",validation:"valid",table:emptyTable,figures:[],sourceIds:["manuscript"],...extra}}
function posterCards(slug:string,t:any){const u=(n:string)=>`/api/workspaces/${slug}/assets/${n}`;return [
 card(`${slug}-p1`,`Clinical / Scientific Need`,`bullets`,`${t.claim}\n\n- Pre-specified endpoints and blinded adjudication.\n- Distribution shifts are measured, not hidden.`,1,0),
 card(`${slug}-p2`,`Formal Objective`,`bullets`,`The constrained objective is\n\n$$${t.equation}$$\n\nAll units, uncertainty intervals, and stopping rules are declared before evaluation.`,1,1),
 card(`${slug}-p3`,`System Architecture`,`bullets-image`,t.methods,2,0,{figures:[{id:"architecture",url:u("architecture.png"),caption:"End-to-end architecture with uncertainty-gated transitions."}]}),
 card(`${slug}-p4`,`Headline Result`,`stats`,`**98.7%** primary endpoint | 95% CI [97.8, 99.3]\n**42 Hz** closed-loop inference | deterministic safety path\n**p < 0.001** paired superiority | Holm corrected`,2,1),
 card(`${slug}-p5`,`Benchmark`,`bullets-table`,`Five independent seeds; bootstrap 95% confidence intervals.`,3,0,{table:{hasHeader:true,caption:"Controlled benchmark; best results in bold.",rows:t.table}}),
 card(`${slug}-p6`,`Ablation & Robustness`,`bullets-two-images`,`- Removing uncertainty calibration increases unsafe interventions by 3.8×.\n- Performance remains stable under 20% sensor dropout.`,3,1,{figureLayout:"two-up",figures:[{id:"bench",url:u("benchmark.png"),caption:"Primary benchmark."},{id:"pipe",url:u("architecture.png"),caption:"Auditable pipeline."}]}),
 card(`${slug}-p7`,`Take-home`,`metric-card`,`**+42%** robust throughput | versus strongest baseline\n**0** critical failures | across stress suite`,3,2),
 card(`${slug}-p8`,`References`,`references`,`Cited foundations: \\cite{vaswani2017attention,brohan2023rt2,pfau2020abinitio,abudayyeh2017rna}.`,1,2)]}
function slideCards(slug:string,t:any){const u=`/api/workspaces/${slug}/assets/`; const defs=[
 ["A Flagship Result","title-slide",t.claim],["Why now?","bullets","Three bottlenecks converge: data scale, calibrated foundation models, and high-bandwidth experimental platforms."],["Research question","two-column",`Can a learned system improve efficacy without relaxing hard safety constraints?\n\n$$${t.equation}$$`],["Evidence-to-action stack","figure-slide",t.methods],["Dataset & protocol","bullets-image","Preregistered splits; site-held-out evaluation; blinded endpoint adjudication; five random seeds."],["Training objective","bullets",`We optimize the task loss jointly with calibration and worst-case robustness. $${t.equation}$`],["Main benchmark","figure-slide","The proposed method leads every pre-specified primary endpoint."],["Ablation study","two-column","Calibration is necessary for safe deployment; ensembling improves robustness rather than merely mean accuracy."],["Stress tests","bullets","- 20% missing sensors\n- unseen operators and sites\n- adversarially selected hard cases\n- temporal drift"],["Safety & uncertainty","bullets-image","Conformal risk control yields an empirical error guarantee and abstains under unsupported inputs."],["Limitations","bullets","Prospective deployment remains necessary. Rare events make tail-risk estimates wide; claims do not extend beyond the tested domain."],["Conclusion","bullets",`${t.claim}\n\nOpen artifacts include protocols, model cards, and deterministic evaluation code.`],["References","references","\\cite{vaswani2017attention,brohan2023rt2,pfau2020abinitio,abudayyeh2017rna}"]];
 return defs.map((d:any[],i:number)=>card(`${slug}-s${i+1}`,d[0],d[1],d[2],null,i,{figures:d[1].includes("image")||d[1]==="figure-slide"?[{id:i%2?"benchmark":"architecture",url:u+(i%2?"benchmark.png":"architecture.png"),caption:"Pre-specified analysis with 95% confidence intervals."}]:[],slideNotes:`Frame ${i+1}: ${d[0]}. State the claim precisely, then separate measured evidence from interpretation. Pause on uncertainty and remind the audience that all endpoints were preregistered. Transition by asking how this evidence changes the deployment decision.`}))}
function paperCards(slug:string,t:any){const u=`/api/workspaces/${slug}/assets/`;return [
 card(`${slug}-a`,`Abstract`,`section`,`${t.claim} We evaluate held-out conditions with preregistered endpoints and report confidence intervals, ablations, and failure modes. The resulting system improves the primary endpoint while preserving an explicit abstention path.`,null,0),
 card(`${slug}-i`,`Introduction`,`section-figure`,`${t.claim} Existing systems trade generality against assurance. We instead make safety constraints first-class optimization objects \\cite{vaswani2017attention,brohan2023rt2}.`,null,1,{figures:[{id:"arch",url:u+"architecture.png",caption:"Architecture and uncertainty gates."}]}),
 card(`${slug}-r`,`Related Work`,`section`,`Foundation models provide transferable representations, neural quantum states offer variational estimators, and programmable RNA effectors support targeted intervention \\cite{pfau2020abinitio,abudayyeh2017rna}. Our contribution is rigorous task-specific control and evaluation.`,null,2),
 card(`${slug}-m`,`Formal Methods`,`section`,`${t.methods}\n\nOur primary optimization is $$${t.equation}$$ where uncertainty is calibrated on a disjoint set. The stopping rule is fixed before test-set access.`,null,3),
 card(`${slug}-e`,`Experiments`,`section-table`,`We compare under identical data, compute, and stopping criteria. Values are means over five seeds; significance uses paired permutation tests with Holm correction.`,null,4,{table:{hasHeader:true,caption:"Primary benchmark. Arrows indicate preferred direction.",rows:t.table}}),
 card(`${slug}-ab`,`Ablations and Robustness`,`section-two-figures`,`Removing calibration causes the largest safety regression. The complete model retains performance under sensor dropout and domain shift (interaction $p=0.18$).`,null,5,{figureLayout:"two-up",figures:[{id:"b",url:u+"benchmark.png",caption:"Benchmark with 95% CI."},{id:"a",url:u+"architecture.png",caption:"Components evaluated in ablation."}]}),
 card(`${slug}-d`,`Discussion`,`section`,`The evidence supports controlled-domain efficacy, not unrestricted autonomy. Tail-risk estimates remain limited by rare events. Prospective multicentre or multi-laboratory validation is the decisive next step.`,null,6),
 card(`${slug}-c`,`Conclusion`,`section`,`A calibrated, constraint-aware architecture can combine foundation-model flexibility with an auditable safety boundary. Artifacts are released to enable exact replication.`,null,7),
 card(`${slug}-ref`,`References`,`references`,`\\cite{vaswani2017attention,brohan2023rt2,pfau2020abinitio,abudayyeh2017rna}`,null,8)]}
async function main(){for(const meta of ELITE_SHOWCASES){const t=topics[meta.id]; await prisma.$transaction(async tx=>{
 await tx.workspace.upsert({where:{id:meta.id},create:{id:meta.id,name:meta.title,authors:t.authors,venue:t.venue,userId:OWNER,bibContent:bib,bibKeys:["vaswani2017attention","brohan2023rt2","pfau2020abinitio","abudayyeh2017rna"]},update:{name:meta.title,authors:t.authors,venue:t.venue,userId:OWNER,bibContent:bib}})
 await tx.output.deleteMany({where:{workspaceId:meta.id}}); await tx.asset.deleteMany({where:{workspaceId:meta.id}}); await tx.documentChunk.deleteMany({where:{workspaceId:meta.id}})
 const outputs=[{id:`${meta.id}-poster`,outputType:"poster",templateId:t.poster,title:meta.title,isActive:true,themeColor:t.color,cards:posterCards(meta.id,t)},{id:`${meta.id}-slides`,outputType:"slides",templateId:"beamer-metropolis",title:`${meta.title}: Evidence, Method, Impact`,isActive:false,themeColor:t.color,cards:slideCards(meta.id,t)},{id:`${meta.id}-paper`,outputType:"paper",templateId:t.paper,title:meta.title,isActive:false,themeColor:t.color,cards:paperCards(meta.id,t)}]
 if(meta.id==="vla-autonomous-surgery") outputs.push({id:`${meta.id}-review`,outputType:"thesis-review",templateId:"posudok-en",title:"Opponent Assessment — SurgiVLA",isActive:false,themeColor:"#003366",cards:Array.from({length:12},(_,i)=>card(`${meta.id}-q${i+1}`,`Criterion ${i+1}`,"section",`Grade **${i<8?"A":"B"}**. The manuscript provides a rigorous, reproducible treatment of ${["novelty","theory","method design","data provenance","statistics","robustness","safety","reproducibility","writing","ethics","limitations","impact"][i]}. Evidence is anchored to manuscript section ${i+1}.`,null,i))} as any)
 for(const o of outputs){await tx.output.create({data:{id:o.id,workspaceId:meta.id,outputType:o.outputType,templateId:o.templateId,title:o.title,isActive:o.isActive,themeColor:o.themeColor,authors:t.authors,venue:t.venue,cards:{create:o.cards.map(({id,...c}:any)=>({id,...c}))}}})}
 for(const file of ["architecture.png","benchmark.png"]) await tx.asset.create({data:{id:`${meta.id}-${file.replace(".png","")}`,workspaceId:meta.id,fileId:file,filename:file,url:`/api/workspaces/${meta.id}/assets/${file}`,kind:"figure",page:1,confidence:"high",caption:file.startsWith("arch")?"Evidence-to-action architecture":"Controlled primary benchmark"}})
 const sections=[t.claim,t.methods,`Primary benchmark: ${t.table.map((r:string[])=>r.join(" | ")).join("; ")}`,"Limitations: controlled-domain evidence does not establish unrestricted deployment safety."]
 for(let i=0;i<sections.length;i++) await tx.documentChunk.create({data:{id:`${meta.id}-chunk-${i+1}`,workspaceId:meta.id,documentId:"manuscript",heading:["Abstract","Methods","Results","Limitations"][i],content:sections[i],tokens:Math.ceil(sections[i].length/4),kind:i===2?"table":"prose",chunkType:i===2?"table":"paragraph",ordinal:i,pageStart:i+1,pageEnd:i+1,sectionPath:["Abstract","Methods","Results","Limitations"][i],sourceElementIds:[`source-${i+1}`],contentHash:`elite-${meta.id}-${i}`}})
 if(meta.id==="vla-autonomous-surgery"){await tx.thesisReview.deleteMany({where:{workspaceId:meta.id}}); const v1Ids=["problem_relevance","objectives_clarity","theoretical_background","methodology_rigor","analytical_execution","results_validity","discussion_relation","originality_contribution","structure_coherence","citations_quality","ethics_transparency","limitations_future_work"],v1Titles=["Relevance and problem formulation","Clarity of objectives and research questions","Theoretical background and literature review","Methodological appropriateness and procedure","Execution and analytical rigor","Validity of results and interpretation","Discussion and relation to objectives","Originality and contribution","Structure, coherence, and academic writing","Citation and bibliography quality","Ethics, reproducibility, and data transparency","Limitations and future work"]; const criteria=v1Ids.map((criterionId:string,i:number)=>({id:`${meta.id}-crit-${i+1}`,criterionId,text:`${v1Titles[i]} — ${sections[Math.min(3,Math.floor(i/3))]}`,rating:i<8?"A":"B",numericScore:i<8?95:85,suggestions:[]})); await tx.thesisReview.create({data:{workspaceId:meta.id,studentName:"Maya Chen",thesisTitle:meta.title,thesisType:"phd",reviewerRole:"opponent",reviewerName:"Prof. Elena Varga",institution:"European Institute of Surgical AI",department:"Robotics and Clinical Systems",grade:"A",suggestedGrade:"A",finalGrade:"A",recommendation:"Recommended for defense with distinction",sections:JSON.stringify(criteria),defenseQuestions:JSON.stringify(["How does the safety guarantee change under non-exchangeable shift?","Which failure mode dominates after force-sensor dropout?","What prospective endpoint would falsify the central claim?","How will calibration be monitored after deployment?"]),summary:t.claim,strengths:JSON.stringify(["Rigorous preregistration","Strong safety architecture","Complete ablations"]),status:"final",language:"en",confidence:.94,discipline:"Medical Robotics",rubricVersion:"eu-phd-12-v1",limitationsSummary:"Ex-vivo evidence; prospective clinical validation remains required."}})}
 }); console.log(`Seeded ${meta.id}: ${meta.outputs.join(", ")}`)} await prisma.$disconnect()}
main().catch(async e=>{console.error(e);await prisma.$disconnect();process.exit(1)})
